# Generated by Django 4.2.4 on 2023-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_region_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_class', models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('BIKE', 'BIKE'), ('3-WHEELER', '3-WHEELER'), ('TRUCK', 'TRUCK'), ('BUS', 'BUS')], max_length=20, null=True)),
                ('fitness_rate', models.CharField(max_length=20, null=True)),
                ('taxtoken_rate', models.CharField(max_length=20, null=True)),
                ('insurance_rate', models.CharField(max_length=20, null=True)),
                ('color_rate', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehicle_fixed_detail',
            name='fuel_type',
            field=models.CharField(choices=[('GAS', 'GAS'), ('PATROL', 'PATROL'), ('DIESEL', 'DIESEL'), ('OCTANE', 'OCTANE')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle_fixed_detail',
            name='vehicle_class',
            field=models.CharField(choices=[('SUV', 'SUV'), ('SEDAN', 'SEDAN'), ('BIKE', 'BIKE'), ('3-WHEELER', '3-WHEELER'), ('TRUCK', 'TRUCK'), ('BUS', 'BUS')], max_length=20, null=True),
        ),
    ]
