# Generated by Django 4.2.4 on 2023-08-20 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pricechart_alter_vehicle_fixed_detail_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=15, null=True)),
                ('admin_id', models.CharField(max_length=11, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
